name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Use Bun
      uses: actions/setup-bun@v2
      with:
        bun-version: latest
    - run: bun i
    - run: bun run build
